crud/urls.py
from django.urls import include, path
from crud import views

app_name = 'crud'

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.addForm, name="add-form-product"),
    path('save', views.save, name='save-add-product'),
    path('<int:id>', views.show, name='show-product'),
    path('edit/<int:id>', views.editForm, name='edit-form-product'),
    path('save-edit/<int:id>', views.saveEdit, name='save-edit-product'),
    path('delete/<int:id>', views.deleteForm, name='delete-form-product'),
    path('delete-confirm/<int:id>', views.deleteConfirmation, name='delete-confirmation-product'),
    path('addClass', views.addClassForm, name="add-class-form-product"),
    path('saveClass', views.saveClass, name='save-class-add-product'),
]

miapp/urls.py
from django.urls import include, path
from miapp import views
# Para que funcione bien la generación de enlaces desde la plantilla
app_name = 'myapp'
urlpatterns = [
    path('', views.index, name="index"),
    path('pagina1', views.pagina1, name="pagina1"),
    path('pagina2', views.pagina2, name="pagina2"),
    path('contacto/', views.contacto, name="contacto"),
    path('productos/', views.listadoProductos, name="listado"),
    path('plantilla/', views.muestraPlantilla, name="plantilla"),
    path('datos/', views.muestraDatos, name="datos"),
    path('captura/<int:n>', views.capturaDatos, name='captura'),
    path('captura/<str:cadena>', views.capturaCadena, name='captura-cadena'),
    path('articulos/<int:agno>/<int:mes>/', views.capturaFecha, name='captura-fecha'),
    path('incluye/', views.incluyePlantilla, name="incluye-plantilla"),
    path('conb/', views.conBootstrap, name="conBootstra")
]

miappdjango/urls.py
''
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from miapp import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls
schema_view = get_swagger_view(title='Pastebin API')
#import miapp
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miapp.urls', namespace='miapp')),
    path('crud/',include('crud.urls', namespace='crud')),
    path('biblioteca/', include('biblioteca.urls')),
    path('genericas/', include('genericas.urls')),
    # aplicación apirest URLBASE /api/
    path('api/', include('apirest.urls', namespace='apirest')),
    url(r'^docs/', schema_view),
    url(r'^doc/', include_docs_urls(title='Mi API Molón'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

miapp/models.py
from django.db import models

# Create your models here.

miapp/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse

# Create your views here.
menu = """<ul>
        <li><a href='/'>Inicio</a></li>
        <li><a href='/contacto/'>Contacto</a></li>
        <li><a href='/productos/'>Productos</a></li>
        <li><a href='/plantilla/'>Uso de Plantilla</a></li>
        <li><a href='/incluye/'>Incluye menu</a></li>
        </ul>"""


def index(request):
    return HttpResponse(
        menu +
        "<h2>Estás en la página principal.</h2>")


def contacto(request):
    return HttpResponse(
        menu +
        "Página de contacto </br>")


def listadoProductos(request):
    return HttpResponse(
        menu +
        "Listado de Productos </br>")


def muestraPlantilla(request):
    mititulo = "Mi título molón"
    template = loader.get_template('miapp/plantilla.html')
    context = {
        'titulo': mititulo
    }
    return HttpResponse(template.render(context, request))


def muestraDatos(request):
    mititulo = "Mi título molón"
    template = loader.get_template('miapp/datos.html')
    context = {
        'titulo': mititulo,
        'subtitulo': "Mi subtítulo aún más molón",
        'entero': 2
    }
    return HttpResponse(template.render(context, request))


def capturaDatos(request, n):
    template = loader.get_template('miapp/captura.html')
    context = {
        'datoCapturado': n,
    }
    return HttpResponse(template.render(context, request))


def capturaCadena(request, cadena):
    template = loader.get_template('miapp/captura.html')
    context = {
        'datoCapturado': cadena,
    }
    return HttpResponse(template.render(context, request))


def capturaFecha(request, agno, mes):
    template = loader.get_template('miapp/fechas.html')
    context = {
        'agnoCapturado': agno,
        'mesCapturado': mes
    }
    return HttpResponse(template.render(context, request))


def incluyePlantilla(request):
    template = loader.get_template('miapp/incluye.html')
    context = {
        'titulo': "Incluyendo el menu"
    }
    return HttpResponse(template.render(context, request))


def pagina1(request):
    template = loader.get_template('miapp/pagina1.html')
    context = {
        'titulo': "Pagina 1"
    }
    return HttpResponse(template.render(context, request))


def pagina2(request):
    template = loader.get_template('miapp/pagina2.html')
    context = {
        'titulo': "Pagina 2"
    }
    return HttpResponse(template.render(context, request))


def conBootstrap(request):
    template = loader.get_template('miapp/conb.html')
    context = {
        'titulo': "Con Bootstrap"
    }
    return HttpResponse(template.render(context, request))

miapp/templates/miapp/captura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dato Capturado</title>
</head>
<body>
<h3>Dato Capturado</h3>
<h2>{{ datoCapturado }}</h2>
</body>
</html>

miapp/templates/miapp/conb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{titulo}}</title>
</head>
<body>
<h3>{{ titulo }}</h3>
{% load bootstrap4 %}
{% bootstrap_css %}

<div class="container">
  <div class="row">
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
  </div>
</div>
{% bootstrap_javascript jquery='full' %}
</body>
</html>

miapp/templates/miapp/datos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{titulo}}</title>
</head>
<body>
<h3>{{ titulo }}</h3>
<h4>{{subtitulo}}</h4>
<h5>{{ entero }}</h5>
</body>
</html>

miapp/templates/miapp/fechas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dato Capturado</title>
</head>
<body>
<h3>Dato Capturado</h3>
<h2>{{ agnoCapturado }}</h2>
<h2>{{ mesCapturado }}</h2>
</body>
</html>

miapp/templates/miapp/footer.html
</body>
</html>

miapp/templates/miapp/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Listado de Productos</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'crud/estilos.css' %}" />
</head>
<body>
{% include "miapp/menu.html" %}

miapp/templates/miapp/incluye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{titulo}}</title>
</head>
<body>
{% include "miapp/menu.html" %}
<h3>{{ titulo }}</h3>
<h2>Subtítulo</h2>
</body>
</html>

miapp/templates/miapp/menu.html
<div>
    <ul>
        <li><a href='/'>Inicio</a></li>
        <li><a href='/contacto/'>Contacto</a></li>
        <li><a href='/productos/'>Productos</a></li>
        <li><a href='/plantilla/'>Uso de Plantilla</a></li>
        <li><a href='/datos/'>Paso de Variables a Vista</a></li>
        <li><a href='/captura/1'>Paso de parámetro numérico por URL</a></li>
        <li><a href='/captura/hola'>Paso de parámetro alfanumérico por URL</a></li>
        <li><a href='/articulos/2019/11/'>Paso de varios parámetros por URL</a></li>
        <li><a href='/incluye/'>Inclusión de plantillas unas con otras</a></li>
        <li><a href='/crud/'>Patron CRUD</a></li>

    </ul>
</div>

miapp/templates/miapp/pagina1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{titulo}}</title>
</head>
<body>
<h3>{{ titulo }}</h3>
<p><a href="/pagina2" >Ir a pagina 2</a></p>
<p><a href="{% url 'miapp:pagina2' %}" >Ir a pagina 2</a></p>
</body>
</html>

miapp/templates/miapp/pagina2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{titulo}}</title>
</head>
<body>
<h3>{{ titulo }}</h3>
<p><a href="/pagina1" >Ir a pagina 1</a></p>
</body>
</html>

miapp/templates/miapp/plantilla.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{titulo}}</title>
    {% load static %}
    <!--link rel="stylesheet" href="/static/miapp/estilos.css"  /-->
    <link rel="stylesheet" href="{% static "miapp/estilos.css" %}"  />
</head>
<body>
<h3>{{ titulo }}</h3>
<h2>Subtítulo</h2>

<p>
<img src="{% static "miapp/by-nc-sa.png" %}" alt="My image"></p>
<script src="{% static "miapp/jquery-3.4.1.js" %}"></script>
<script>
    $(document).ready(function () {
        console.log("Ready cargado")
    })
</script>
</body>
</html>