crud/urls.py
from django.urls import include, path
from crud import views

app_name = 'crud'

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.addForm, name="add-form-product"),
    path('save', views.save, name='save-add-product'),
    path('<int:id>', views.show, name='show-product'),
    path('edit/<int:id>', views.editForm, name='edit-form-product'),
    path('save-edit/<int:id>', views.saveEdit, name='save-edit-product'),
    path('delete/<int:id>', views.deleteForm, name='delete-form-product'),
    path('delete-confirm/<int:id>', views.deleteConfirmation, name='delete-confirmation-product'),
    path('addClass', views.addClassForm, name="add-class-form-product"),
    path('saveClass', views.saveClass, name='save-class-add-product'),
]

miappdjango/urls.py
''
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from miapp import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls
schema_view = get_swagger_view(title='Pastebin API')
#import miapp
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miapp.urls', namespace='miapp')),
    path('crud/',include('crud.urls', namespace='crud')),
    path('biblioteca/', include('biblioteca.urls')),
    path('genericas/', include('genericas.urls')),
    # aplicación apirest URLBASE /api/
    path('api/', include('apirest.urls', namespace='apirest')),
    url(r'^docs/', schema_view),
    url(r'^doc/', include_docs_urls(title='Mi API Molón'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crud/models.py
from django.db import models


# Create your models here.
from django.urls import reverse


class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    precio = models.FloatField(null=True, blank=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of Product.
        """
        return reverse('apirest:producto-detail', args=[str(self.id)])

    def __str__(self):
        return str(self.id) + ":" + self.nombre


from rest_framework import serializers, viewsets


#class ProductoSerializer(serializers.HyperlinkedModelSerializer):
class ProductoSerializer(serializers.ModelSerializer):
    class Meta:
        model = Producto
        fields = ('id', 'nombre', 'precio')


class ProductViewSet(viewsets.ModelViewSet):
    """
    retrieve:
        Return the given product.

    list:
        Return a list of all product.

    create:
        Create a new product.

    destroy:
        Delete a product.

    update:
        Update a product.

    partial_update:
        Update a product.
    """

    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer

crud/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

from crud.models import Producto
from .form import ProductForm
from django.shortcuts import redirect
# Create your views here.

def index(request):
    mititulo = "Listado de Productos"
    template = loader.get_template('crud/index.html')
    """
    productos = [
        {
            'id': 2,
            'nombre': "HDD 4TB",
            'precio': 36.9
        },
        {
            'id': 3,
            'nombre': "HDD 2TB",
            'precio': 16.9
        },
        {
            'id': 4,
            'nombre': "HDD 1TB",
            'precio': 9.9
        },
    ]
    """
    productos= Producto.objects.all()
    context = {
        'titulo': mititulo,
        'productos': productos
    }
    return HttpResponse(template.render(context, request))
def addForm(request):
    mititulo = "Formulario de alta de Productos"
    template = loader.get_template('crud/addForm.html')
    producto = {
        'nombre': "",
        'precio': 0
    }
    context = {
        'titulo': mititulo,
        'producto': producto
    }
    return HttpResponse(template.render(context, request))
def addClassForm(request):
    mititulo = "Formulario de alta de Productos"
    template = loader.get_template('crud/addClassForm.html')
    productoForm = ProductForm()

    producto = {
        'nombre': "",
        'precio': 0
    }
    context = {
        'titulo': mititulo,
        'producto': producto,
        'productoForm': productoForm
    }
    return HttpResponse(template.render(context, request))
def show(request, id):
    mititulo = "Mostrar Producto"
    template = loader.get_template('crud/show.html')
    """
    producto = {
        'id': id,
        'nombre': "HDD 4TB",
        'precio': 35
    }
    """
    producto= Producto.objects.get(pk=id)
    context = {
        'titulo': mititulo,
        'producto': producto
    }
    return HttpResponse(template.render(context, request))
def save(request):
    print(request.POST)
    mititulo = "Confirmación de alta de Producto"
    template = loader.get_template('crud/save.html')
    """
    producto = request.POST
    producto.id= 2

    producto = {
        'id': 2,
        'nombre': "HDD 4TB",
        'precio': 35
    }
    """
    # print(request.POST)
    producto = Producto(nombre=request.POST['nombre'], precio=request.POST['precio'])
    producto.save()
    context = {
        'titulo': mititulo,
        'producto': producto
    }
    return HttpResponse(template.render(context, request))
def saveClass(request):

    producto = ProductForm(request.POST)
    if request.method == "POST" and producto.is_valid():
        print("Producto válido")
        print(request.POST)
        print(request.POST['nombre'])
        #print(producto.precio)
        mititulo = "Confirmación de Producto"
        template = loader.get_template('crud/saveClass.html')
        # return HttpResponse(template.render(context, request))
        # return redirect('crud:index')
    else:
        print("Producto Inválido")
        mititulo = "Formulario de Alta de Producto"
        template = loader.get_template('crud/addClassForm.html')

    context = {
        'titulo': mititulo,
        'producto': producto
    }
    return HttpResponse(template.render(context, request))


def saveEdit(request, id):
    mititulo = "Producto guardado"
    template = loader.get_template('crud/save.html')
    producto= Producto.objects.get(pk=id)
    producto.nombre=request.POST['nombre']
    producto.precio=request.POST['precio']
    producto.save()
    """
    producto = {
        'id': id,
        'nombre': "HDD 4TB",
        'precio': 35
    }
    """
    context = {
        'titulo': mititulo,
        'producto': producto
    }
    return HttpResponse(template.render(context, request))
def editForm(request, id):
    mititulo = "Formulario de alta de Productos"
    template = loader.get_template('crud/editForm.html')
    producto = Producto.objects.get(pk=id)
    """
    producto = {
        'id': id,
        'nombre': "HDD 4TB",
        'precio': 35
    }
    """
    context = {
        'titulo': mititulo,
        'producto': producto
    }
    return HttpResponse(template.render(context, request))
def deleteForm(request, id):
    mititulo = "Confirmación de Borrado de Producto"
    template = loader.get_template('crud/deleteForm.html')

    producto = Producto.objects.get(pk=id)
    """
    producto = {
        'id': id,
        'nombre': "HDD 4TB",
        'precio': 35
    }
    """
    context = {
        'titulo': mititulo,
        'producto': producto
    }
    return HttpResponse(template.render(context, request))
def deleteConfirmation(request, id):
    mititulo = "Confirmación de borrado de Producto"
    template = loader.get_template('crud/deleteConfirm.html')
    """
    producto = {
        'id': id,
        'nombre': "HDD 4TB",
        'precio': 35
    }
    """
    producto = Producto.objects.get(pk=id)
    producto.delete()
    context = {
        'titulo': mititulo,
        'producto': producto
    }
    return HttpResponse(template.render(context, request))

from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from .models import Producto, ProductoSerializer

@csrf_exempt
def indexApi(request):
    try:
        productos = Producto.objects.all()
    except Producto.DoesNotExist:
        return HttpResponse(status=404)
    if request.method == 'GET':
        serializer = ProductoSerializer(productos, many=True, context={'request': request})
        return JsonResponse(serializer.data, safe=False, status=200)
    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = ProductoSerializer(data=data, context={'request': request})
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)
@csrf_exempt
def detailApi(request, pk):

    """
    Retrieve, update or delete a code snippet.
    """
    try:
        producto = Producto.objects.get(pk=pk)
    except Producto.DoesNotExist:
        return HttpResponse(status=404)
    if request.method == 'GET':
        serializer = ProductoSerializer(producto)
        return JsonResponse(serializer.data)
    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = ProductoSerializer(producto, data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=200)
        return JsonResponse(serializer.errors, status=400)
    elif request.method == 'DELETE':
        producto.delete()
        producto.id=pk
        serializer = ProductoSerializer(producto)
        return JsonResponse(serializer.data, status=204)

crud/templates/crud/addClassForm.html
{% include "miapp/header.html" %}
<form action="{% url 'crud:save-class-add-product' %}" method="post">
        {% csrf_token %}
{% for field in productoForm %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
<input type="submit" name="submit" id="submit" value="Enviar" class="btn btn-primary"/>
</form>
<p><a href="{% url 'crud:index' %}"><button type="button"  class="btn btn-primary">Volver al listado</button></a></p>
{% include "miapp/footer.html" %}

crud/templates/crud/addForm.html
{% include "miapp/header.html" %}
<h2>{{ titulo }}</h2>

<div>
    <form action="{% url 'crud:save-add-product' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" id="nombre" class="form-control"
                   aria-describedby="nombreHelp"
                   placeholder="introduzca nombre" value="{{  producto.nombre }}"/>
            <small id="nombreHelp" class="form-text text-muted">Este será el nombre que le damos al producto.</small>
        </div>
        <div class="form-group">
            <label for="precio">Precio</label>
            <input type="number" name="precio" aria-describedby="precioHelp"
                   id="precio" value="{{  producto.precio }}"
                   class="form-control"/>
            <small id="precioHelp" class="form-text text-muted">Este será el precio que le damos al producto.</small>
        </div>
        <input type="submit" name="submit" id="submit" value="Enviar" class="btn btn-primary"/>
    </form>
    <p><a href="{% url 'crud:index' %}"><button type="button"  class="btn btn-primary">Volver al listado</button></a></p>
</div>
{% include "miapp/footer.html" %}

crud/templates/crud/deleteConfirm.html
{% include "miapp/header.html" %}

<h2>{{ titulo }}</h2>

<div>
    <div>
        <label for="iden">ID: {{  producto.id }}</label>
    </div>
    <div>
        <label for="nombre">Nombre: {{  producto.nombre }}</label>
    </div>
    <div>
        <label for="precio">Precio: {{  producto.precio }}</label>
    </div>
    <p><a href="{% url 'crud:index' %}"><button type="button" class="btn btn-primary">Volver al listado</button></a></p>
</div>
{% include "miapp/footer.html" %}

crud/templates/crud/deleteForm.html
{% include "miapp/header.html" %}

<h2>{{ titulo }}</h2>

<div>
    <form action="{% url 'crud:delete-confirmation-product' producto.id %}" method="post">
        {% csrf_token %}
        <div>
            <label for="iden">ID</label>
            <input type="text" name="iden" id="iden" disabled
                   placeholder="introduzca nombre" value="{{  producto.id }}"/>
        </div>
        <div>
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" id="nombre" disabled
                   placeholder="introduzca nombre" value="{{  producto.nombre }}"/>
        </div>
        <div>
            <label for="precio">Precio</label>
            <input type="number" name="precio" id="precio"
                   value="{{  producto.precio }}" disabled/>
        </div>
        <input type="submit" name="submit" id="submit" value="Borrar" class="btn btn-danger"/>
    </form>
    <p><a href="/crud/"><button type="button" class="btn btn-primary">Volver al listado</button></a></p>
</div>

{% include "miapp/footer.html" %}

crud/templates/crud/editForm.html
{% include "miapp/header.html" %}

<h2>{{ titulo }}</h2>

<div>
    <form action="{% url 'crud:save-edit-product' producto.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="iden">ID</label>
            <input  type="text" name="iden" id="iden" disabled class="form-control"
                    placeholder="introduzca nombre" value="{{  producto.id }}"
                    aria-describedby="idHelp"/>
            <small id="idHelp" class="form-text text-muted">Este es el id que le damos al producto.</small>
        </div>
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input  type="text" name="nombre" id="nombre" class="form-control"
                    placeholder="introduzca nombre" value="{{  producto.nombre }}"
                    aria-describedby="nombreHelp"/>
            <small id="nombreHelp" class="form-text text-muted">Este será el nombre que le damos al producto.</small>
        </div>
        <div class="form-group">
            <label for="precio">Precio</label>
            <input  type="number" name="precio" id="precio" class="form-control"
                    value="{{  producto.precio }}" aria-describedby="precioHelp"/>
            <small id="precioHelp" class="form-text text-muted">Este será el precio que le damos al producto.</small>
        </div>
        <input type="submit" name="submit" id="submit" value="Enviar" class="btn btn-warning"/>
    </form>
    <p><a href="{% url 'crud:index' %}"><button type="button" class="btn btn-primary">Volver al listado</button></a></p>
</div>

{% include "miapp/footer.html" %}

crud/templates/crud/index.html
{% include "miapp/header.html" %}
<h2>{{ titulo }}</h2>

<div>
    <p><a href="{% url 'crud:add-form-product' %}"><button type="button" class="btn btn-primary">Añadir</button></a></p>
<p><a href="{% url 'crud:add-class-form-product' %}"><button type="button" class="btn btn-primary">Añadir Form con Clase</button></a></p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Precio</th>
                <th scope="col">Operaciones</th>
            </tr>
        </thead>
        <tbody>
        {% for producto in productos %}
            <tr>
                <td scope="row">{{ producto.id }}</td>
                <td>{{ producto.nombre }}</td>
                <td>{{ producto.precio }}</td>
                <td>
                    <a href="{% url 'crud:show-product' producto.id %}"><button class="btn btn-primary">Mostrar</button></a>
                    <a href="{% url 'crud:edit-form-product' producto.id %}"><button class="btn btn-warning">Editar</button></a>
                    <a href="{% url 'crud:delete-form-product' producto.id %}"><button class="btn btn-danger">Borrar</button></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% include "miapp/footer.html" %}

crud/templates/crud/save.html
{% include "miapp/header.html" %}

<h2>{{ titulo }}</h2>

<div>
    <div>
        <label for="iden">ID: {{  producto.id }}</label>
    </div>
    <div>
        <label for="nombre">Nombre: {{  producto.nombre }}</label>
    </div>
    <div>
        <label for="precio">Precio: {{  producto.precio }}</label>
    </div>
    <p><a href="{% url 'crud:index' %}"><button type="button"  class="btn btn-primary">Volver al listado</button></a></p>
</div>

{% include "miapp/footer.html" %}

crud/templates/crud/saveClass.html
{% include "miapp/header.html" %}

<h2>{{ titulo }}</h2>

<div>
    <div>
        <label for="iden">ID: {{  producto.id }}</label>
    </div>
    <div>
        <label for="nombre">Nombre: {{  producto.nombre.value }}</label>
    </div>
    <div>
        <label for="precio">Precio: {{  producto.precio.value }}</label>
    </div>
    <p><a href="{% url 'crud:index' %}"><button type="button"  class="btn btn-primary">Volver al listado</button></a></p>
</div>

{% include "miapp/footer.html" %}

crud/templates/crud/show.html
{% include "miapp/header.html" %}

<h2>{{ titulo }}</h2>

<div>
    <div>
        <label for="iden">ID: {{  producto.id }}</label>
    </div>
    <div>
        <label for="nombre">Nombre: {{  producto.nombre }}</label>
    </div>
    <div>
        <label for="precio">Precio: {{  producto.precio }}</label>
    </div>
    <p><a href="{% url 'crud:index' %}"><button type="button" class="btn btn-primary">Volver al listado</button></a></p>
</div>

{% include "miapp/footer.html" %}