crud/urls.py
from django.urls import include, path
from crud import views

app_name = 'crud'

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.addForm, name="add-form-product"),
    path('save', views.save, name='save-add-product'),
    path('<int:id>', views.show, name='show-product'),
    path('edit/<int:id>', views.editForm, name='edit-form-product'),
    path('save-edit/<int:id>', views.saveEdit, name='save-edit-product'),
    path('delete/<int:id>', views.deleteForm, name='delete-form-product'),
    path('delete-confirm/<int:id>', views.deleteConfirmation, name='delete-confirmation-product'),
    path('addClass', views.addClassForm, name="add-class-form-product"),
    path('saveClass', views.saveClass, name='save-class-add-product'),
]

genericas/urls.py
from django.urls import path
from genericas.views import *


app_name = 'genericas'




urlpatterns = [
    path('', ClienteListView.as_view(), name='cliente-list'),
    path('add', ClienteCreate.as_view(),name="cliente-create"),
    path('<int:pk>', ClienteDetailView.as_view(),name='cliente-detail'),
    path('update/<int:pk>',ClienteUpdate.as_view(), name='cliente-update-form'),
    path('delete/<int:pk>', ClienteDelete.as_view(), name='cliente-delete'),

    path('addComplejo', LibroCreate.as_view(),name="libro-create-complejo"),
    path('libro/<int:pk>', LibroDetailView.as_view(),name='libro-detail'),
]

miappdjango/urls.py
''
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from miapp import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls
schema_view = get_swagger_view(title='Pastebin API')
#import miapp
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miapp.urls', namespace='miapp')),
    path('crud/',include('crud.urls', namespace='crud')),
    path('biblioteca/', include('biblioteca.urls')),
    path('genericas/', include('genericas.urls')),
    # aplicación apirest URLBASE /api/
    path('api/', include('apirest.urls', namespace='apirest')),
    url(r'^docs/', schema_view),
    url(r'^doc/', include_docs_urls(title='Mi API Molón'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

genericas/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Cliente (models.Model):
    nombre = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.nombre
    def get_absolute_url(self):
        """Devuelve el URL a una instancia particular de
           Cliente"""
        return reverse('genericas:cliente-detail', args=[str(self.id)])

genericas/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from biblioteca.models import Libro
from genericas.models import Cliente

class ClienteListView(ListView):
    model = Cliente
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ClienteCreate(CreateView):
    model = Cliente
    fields = ['nombre', 'apellidos']



class ClienteDetailView(DetailView):
    model = Cliente
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ClienteUpdate(UpdateView):
    model = Cliente
    fields = ['nombre', 'apellidos']
    template_name_suffix = '_update_form'

class ClienteDelete(DeleteView):
    model = Cliente
    success_url = reverse_lazy('genericas:cliente-list')


class LibroCreate(CreateView):
    model = Libro
    fields = ['nombre', 'escritor', 'generos']

class LibroDetailView(DetailView):
    model = Libro
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

genericas/templates/genericas/cliente_confirm_delete.html
<form method="post">{% csrf_token %}
 <p>Estás seguro que quieres borrar el cliente "{{ object.nombre }}"?</p>
 <input type="submit" value="Confirmar" />
</form>
<a href="{% url 'genericas:cliente-list' %}">Volver</a>

genericas/templates/genericas/cliente_detail.html
<h1>Detalles del Cliente</h1>
<p>{{ object.nombre }}</p>
<p>{{ object.apellidos }}</p>
<a href="{% url 'genericas:cliente-list'  %}">Volver</a>

genericas/templates/genericas/cliente_form.html
<form method="post">{% csrf_token %}
 {{ form.as_p }}
 <input type="submit" value="Guardar" />
</form>
<a href="{% url 'genericas:cliente-list' %}">Volver</a>

genericas/templates/genericas/cliente_list.html
<h1>Clientes</h1>
<a href="{% url 'genericas:cliente-create' %}">Crear Cliente</a>
<ul>
{% for cliente in object_list %}
 <li>
     <a href="{% url 'genericas:cliente-detail' cliente.id %}">{{ cliente.nombre }}</a>
     <a href="{% url 'genericas:cliente-update-form' cliente.id %}"><button>Editar</button></a>
     <a href="{% url 'genericas:cliente-delete' cliente.id %}"><button>Borrar</button></a>
 </li>
{% empty %}
 <li>No hay clientes todavía</li>
{% endfor %}
</ul>

<a href="{% url 'genericas:libro-create-complejo' %}">Crear Libro Complejo</a>

genericas/templates/genericas/cliente_update_form.html
<form method="post">{% csrf_token %}
 {{ form.as_p }}
 <input type="submit" value="Guardar" />
</form>
<a href="{% url 'genericas:cliente-list' %}">Volver</a>