biblioteca/urls.py
from django.urls import path
from biblioteca.views import *


app_name = 'biblioteca'

urlpatterns = [
    path('', GenreListView.as_view(), name='genre-list'),
    path('genre/<int:pk>', GenreDetailView.as_view(), name='genre-detail'),
    path('genre/create', GenreCreate.as_view(), name='genre-create'),
    path('genre/update/<int:pk>', GenreUpdate.as_view(), name='genre-update-form'),
    path('genre/delete/<int:pk>', GenreDelete.as_view(), name='genre-delete'),
    path('genre/list', simple_list, name='genre-list2'),
    path('genre/list3', listado_sencillo, name='genre-list3'),
    path('genre/api', list_json, name='genre-list-api'),
    path('genre/api/<int:pk>', get_json, name='genre-get-api'),
    path('lenguajes/', presentaLenguajes, name='genre-list'),
]

crud/urls.py
from django.urls import include, path
from crud import views

app_name = 'crud'

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.addForm, name="add-form-product"),
    path('save', views.save, name='save-add-product'),
    path('<int:id>', views.show, name='show-product'),
    path('edit/<int:id>', views.editForm, name='edit-form-product'),
    path('save-edit/<int:id>', views.saveEdit, name='save-edit-product'),
    path('delete/<int:id>', views.deleteForm, name='delete-form-product'),
    path('delete-confirm/<int:id>', views.deleteConfirmation, name='delete-confirmation-product'),
    path('addClass', views.addClassForm, name="add-class-form-product"),
    path('saveClass', views.saveClass, name='save-class-add-product'),
]

genericas/urls.py
from django.urls import path
from genericas.views import *


app_name = 'genericas'




urlpatterns = [
    path('', ClienteListView.as_view(), name='cliente-list'),
    path('add', ClienteCreate.as_view(),name="cliente-create"),
    path('<int:pk>', ClienteDetailView.as_view(),name='cliente-detail'),
    path('update/<int:pk>',ClienteUpdate.as_view(), name='cliente-update-form'),
    path('delete/<int:pk>', ClienteDelete.as_view(), name='cliente-delete'),

    path('addComplejo', LibroCreate.as_view(),name="libro-create-complejo"),
    path('libro/<int:pk>', LibroDetailView.as_view(),name='libro-detail'),
]

miappdjango/urls.py
''
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from miapp import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls
schema_view = get_swagger_view(title='Pastebin API')
#import miapp
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miapp.urls', namespace='miapp')),
    path('crud/',include('crud.urls', namespace='crud')),
    path('biblioteca/', include('biblioteca.urls')),
    path('genericas/', include('genericas.urls')),
    # aplicación apirest URLBASE /api/
    path('api/', include('apirest.urls', namespace='apirest')),
    url(r'^docs/', schema_view),
    url(r'^doc/', include_docs_urls(title='Mi API Molón'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

biblioteca/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
import uuid  # Requerido por las BooksInstances
from rest_framework import serializers, viewsets

class Libro(models.Model):
    #Atributo de cada Libro, marca que es un conjunto de caracteres con un máximo de 200pk
    nombre = models.CharField(max_length=200)
    escritor= models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
    generos = models.ManyToManyField('Genero', help_text="Select a genre for this book", null=True, blank=True)
    #Función de conversión a cadena del objeto
    def __str__(self):
        return self.nombre
    def get_absolute_url(self):
        """Devuelve el URL a una instancia particular de
           Libro"""
        return reverse('genericas:libro-detail', args=[str(self.id)])

class LibroSerializer(serializers.ModelSerializer):
    class Meta:
        model = Libro
        fields = ('id', 'nombre', 'escritor', 'generos')

class Autor(models.Model):
    nombre= models.CharField(max_length=100)
    def __str__(self):
        return self.nombre
class AutorSerializer(serializers.ModelSerializer):
    class Meta:
        model = Autor
        fields = ('id', 'nombre')

class Genero (models.Model):
    nombre=models.CharField(max_length=100)
    def __str__(self):
        return self.nombre




#class ProductoSerializer(serializers.HyperlinkedModelSerializer):
class GeneroSerializer(serializers.ModelSerializer):
    class Meta:
        model = Genero
        fields = ('id', 'nombre')

class Language(models.Model):
    """
    Modelo que representa un idioma por ejemplo español
    """
    name = models.CharField(max_length=200, help_text="Introduce un nombre de idioma")
    codigo = models.CharField(max_length=6, help_text="Introduce un código de idioma")

    def __str__(self):
        """
        Cadena que representa a la instancia particular del modelo (p. ej en el sitio de Administración)
        """
        return self.name

class Genre(models.Model):
    """Modelo que representa un género literario (p. ej. ciencia ficción, poesía, etc.)."""
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        """Cadena que representa a la instancia particular del modelo (p. ej en
        el sitio de Administración)"""
        return self.name
    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('biblioteca:genre-detail', args=[str(self.id)])

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('biblioteca:author-detail', args=[str(self.id)])
    def __str__(self):
        """String for representing the Model object."""
        return '%s, %s' % (self.last_name, self.first_name)

class Book(models.Model):
    """Modelo que representa un libro (pero no un Ejemplar específico)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
    # 'Author' es un string, en vez de un objeto, porque la clase Author aún no ha sido declarada.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbninternational.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField, porque un género puede contener muchos libros y un libro puede cubrir varios géneros.
    # La clase Genre ya ha sido definida, entonces podemos especificar el objeto arriba
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    def __str__(self):
        """String que representa al objeto Book"""
        return self.title

    def get_absolute_url(self):
        """Devuelve el URL a una instancia particular de
           Book"""
        return reverse('biblioteca:book-detail', args=[str(self.id)])

class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Identificativo único para este libro físico")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Disponibilidad del libro')

    class Meta:
        ordering = ["due_back"]

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id, self.book.title)

class Ordenador(models.Model):
    marca= models.CharField(max_length=100)
    modelo=models.CharField(max_length=100)
    precio = models.FloatField(null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.marca + ": " +self.modelo


class Noticia(models.Model):
    titulo= models.CharField(max_length=20, default='')
    tags = models.ManyToManyField('Tag', blank=True)

class Tag(models.Model):
    nombre = models.CharField(max_length=20, default='')
    noticias = models.ManyToManyField('Noticia', through=Noticia.tags.through, blank=True)

class Test1(models.Model):
    nombre= models.CharField(max_length=20, default='')
    tests2 = models.ManyToManyField('Test2', blank=True)

class Test2(models.Model):
    nombre = models.CharField(max_length=20, default='')
    tests1 = models.ManyToManyField('Test1', through=Test1.tests2.through, blank=True)

biblioteca/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render
from django_tables2 import RequestConfig
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from django.template import loader
from django.http import HttpResponse

from biblioteca.models import Genre, Language


def presentaLenguajes(request):
    template = loader.get_template('biblioteca/language_list.html')
    listado= Language.objects.all()
    context = {'listado': listado}
    return HttpResponse(template.render(context, request))

class GenreListView(ListView):

    model = Genre
    paginate_by = 100  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class GenreDetailView(DetailView):

    model = Genre

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context



class GenreCreate(CreateView):
    model = Genre
    fields = ['name']


class GenreUpdate(UpdateView):
    model = Genre
    fields = ['name']
    template_name_suffix = '_update_form'

class GenreDelete(DeleteView):
    model = Genre
    success_url = reverse_lazy('biblioteca:genre-list')

import django_tables2 as tables

class GenreTable(tables.Table):
    class Meta:
        model = Genre

def simple_list(request):

    table = GenreTable(Genre.objects.all())
    RequestConfig(request).configure(table)
    return render(request, 'biblioteca/simple_list.html', {'table': table})


@csrf_exempt
def list_json(request):
    data={'error':"No hay Datos"}
    status=500
    try:
        if(request.method=='GET'):
            #data['objetos']=serialize('json', Genre.objects.all())
            data['objetos'] = list(Genre.objects.all().values('id','name'))

            print(data['objetos'])
        if(request.method=="POST"):
            data['objeto']={}
        status=200
        del data['error']
    except:
        print ('Fallo al acceder a la BBDD')
    return JsonResponse(data,status=status)

@csrf_exempt
def get_json(request,pk):
    data = {'error': "No hay Datos"}
    status = 500
    try:
        #data['objetos']=serialize('json', Genre.objects.all())
        data['objeto'] = list(Genre.objects.filter(id=pk).values('id','name'))[0]
        #print(data['objeto'])
        status=200
        del data['error']
    except:
        print ('Fallo al acceder a la BBDD')
    return JsonResponse(data,status=status)

@csrf_exempt
def create_json(request):
    data = {'error': 'No hay datos'}
    status = 500
    try:
        data_post = json.loads(request.body)
        try:
            status = 200
            print(data_post)
        except:
            data['error'] = "No se puede cargar el dato desde la BBDD"
    except:
        print('nope')
        data['error']="No se puede cargar el código JSON"
    return JsonResponse(data, status=status)


def listado_sencillo(request):
    listado=Genre.objects.all()
    template = loader.get_template('biblioteca/genre_list2.html')
    context = {'listado': listado}
    return HttpResponse(template.render(context, request))

biblioteca/templates/biblioteca/base.html
{% load staticfiles %}<!DOCTYPE html>
    <html>
        <head>
            <title>Ejemplo de CRUD de Géneros Literarios</title>
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
            <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
            <!--link rel="stylesheet" href="{% static 'css/blog.css' %}"-->
        </head>
        <body>
            <div class="page-header">
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <a class="navbar-brand" href="#">Gestión de Biblioteca</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'index' %}">Inicio</a></li>
                    </ul>
                      <ul class="nav navbar-nav">
                        <!-- Cambiar a un enlace nombrado por urls -->
                        <li><a href="/libros">Libros</a></li>
                        <li><a href="{% url 'biblioteca:genre-list' %}">Biblioteca</a></li>

                        <li><a href="{% url 'biblioteca:genre-list2' %}">Biblioteca DataTable</a></li>
                        <li><a href="{% url 'biblioteca:genre-list3' %}">Listado de Géneros</a></li>
                    </ul>
                  </div>
                </nav>
            </div>
            <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                    {% block content %}
                    {% endblock %}
                    </div>
                </div>
            </div>
        </body>
    </html>

biblioteca/templates/biblioteca/genre_confirm_delete.html
{% extends 'biblioteca/base.html' %}
{% block content %}
    <p><a href="{% url 'biblioteca:genre-list' %}" class="btn btn-default">Volver al Listado</a> </p>
    <h2>Formulario de Confirmación de Borrado de Género</h2>
    <form method="post">{% csrf_token %}
        <p>Estás seguro que quieres borrar el género "{{ object.name }}"?</p>
        <input type="submit" value="Confirmar" class="btn btn-danger" />
    </form>
{% endblock %}

biblioteca/templates/biblioteca/genre_detail.html
{% extends 'biblioteca/base.html' %}
{% block content %}
    <p><a href="{% url 'biblioteca:genre-list' %}"  class="btn btn-default">Volver al Listado</a> </p>
    <h1>Detalles del Género</h1>
    <label>Nombre:</label><p>{{ object.name }}</p>
{% endblock %}

biblioteca/templates/biblioteca/genre_form.html
{% extends 'biblioteca/base.html' %}
{% block content %}
    <p><a href="{% url 'biblioteca:genre-list' %}"  class="btn btn-default">Volver al Listado</a> </p>
    <h2>Formulario de Alta de Géneros</h2>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar" class="btn btn-warning" />
    </form>
{% endblock %}

biblioteca/templates/biblioteca/genre_list.html
{% extends 'biblioteca/base.html' %}
{% block content %}
    <h1>Géneros</h1>
    <a href="{% url 'biblioteca:genre-create' %}" class="btn btn-success">Crear Género</a>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Operaciones</th>
                </tr>
            </thead>
        {% for genre in object_list %}
            <tr>
                <td><a href="{% url 'biblioteca:genre-detail'  genre.id %}">{{ genre.name }}</a>
                </td>
                <td>
                    <a href="{% url 'biblioteca:genre-detail'  genre.id %}" class="btn btn-info">Detalle</a>&nbsp;
                    <a href="{% url 'biblioteca:genre-update-form'  genre.id %}" class="btn btn-warning">Editar</a>&nbsp;
                    <a href="{% url 'biblioteca:genre-delete'  genre.id %}"class="btn btn-danger">Borrar</a>
                </td>
            </tr>
        {% empty %}
            <td colspan="2">No hay Géneros todavía</td>
        {% endfor %}
        </table>
    </div>
{% endblock %}

biblioteca/templates/biblioteca/genre_list2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Listado de Géneros</title>
</head>
<body>
<p><a href="{% url 'biblioteca:genre-create' %}">Añadir</a></p>
{{ listado }}
<ul>
{% for genre in listado %}
    <li><a href="{% url 'biblioteca:genre-detail'  genre.id %}">{{ genre.name }}</a>: Operaciones:<a href="{% url 'biblioteca:genre-detail'  genre.id %}">Detalle</a><a href="{% url 'biblioteca:genre-update-form'  genre.id %}">Editar</a><a href="{% url 'biblioteca:genre-delete'  genre.id %}">Borrar</a></li>
{% empty %}
    <li>No hay Géneros todavía</li>
{% endfor %}
</ul>
</body>
</html>

biblioteca/templates/biblioteca/genre_update_form.html
{% extends 'biblioteca/base.html' %}
{% block content %}
    <p><a href="{% url 'biblioteca:genre-list' %}"  class="btn btn-default">Volver al Listado</a> </p>
    <h2>Formulario de Edición de Géneros</h2>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Actualizar"  class="btn btn-warning"/>
    </form>
{% endblock %}

biblioteca/templates/biblioteca/index.html
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<ul>
    <li><a href="{% url 'home:index' %}">Home</a></li>
    <li><a href="home/2">Enlace con numero</a></li>
    <li><a href="{% url 'home:detail' 2 %}">Enlace con numero v2</a></li>
    <li><a href="home/pepe">Enlace con nombre</a></li>
    <li><a href="{% url 'home:nombre' 'pepe' %}">Enlace con nombre v2</a></li>
    <li><a href="{% url 'polls:index' %}">Polls</a></li>
    <!-- Cambiar a un enlace nombrado por urls -->
    <li><a href="/libros">Libros</a></li>
    <li><a href="{% url 'genre-list' %}">Biblioteca</a></li>

    <li><a href="{% url 'genre-list2' %}">Biblioteca DataTable</a></li>
    <li><a href="{% url 'genre-list3' %}">Listado de Géneros</a></li>
    <li><a href="{% url 'home:devuelvejson' %}">Devuelve JSON</a></li>
    <li><a href="{% url 'tool-list' %}">Listado de Posts (MongoDB)</a></li>
    <li><a href="{% url 'snippet-list' %}">Listado de Snippets</a></li>
    <!-- Autenticación -->
    <li><a href="{% url 'rest_login' %}">Login</a></li>
    <li><a href="{% url 'rest_logout' %}">Logout</a></li>
</ul>
<h3>{{ titulo }}</h3>
<h2>Subtítulo</h2>

biblioteca/templates/biblioteca/language_list.html
<h1>Listado de lenguajes</h1>
{{ listado }}
<ul>
{% for lenguaje in listado %}
   <li>ID {{ lenguaje.id }}: {{ lenguaje.name }}</li>
{% empty %}
    <li>No hay Lenguajes todavía</li>
{% endfor %}
</ul>

biblioteca/templates/biblioteca/libro_detail.html
<h1>Detalles del Libro</h1>
<p>{{ object.nombre }}</p>
<p>{{ object.escritor.nombre }}</p>
<a href="{% url 'genericas:cliente-list'  %}">Volver</a>

biblioteca/templates/biblioteca/libro_form.html
<form method="post">{% csrf_token %}
 {{ form.as_p }}
 <input type="submit" value="Guardar" />
</form>
<a href="{% url 'genericas:cliente-list' %}">Volver</a>

biblioteca/templates/biblioteca/simple_list.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>Listado de géneros</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    {% render_table table %}
                </div>
            </div>
        </div>
    </body>
</html>